# Copyright 2023 Canonical Ltd.
# See LICENSE file for licensing details.

name: Release to latest/edge

env:
  RELEASE: edge

on:
  push:
    branches:
      - main

jobs:
  ci-test-and-build:
    uses: ./.github/workflows/ci.yaml
    with:
      branch: main

  release:
    name: Release snap
    runs-on: ubuntu-latest
    needs:
      - ci-test-and-build
    steps:
      - name: Download built snap file
        uses: actions/download-artifact@v3
        with:
          name: ${{ needs.ci-test-and-build.outputs.snap-file }}
          path: .
      - name: Publish built snap to Store
        uses: snapcore/action-publish@v1
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.STORE_LOGIN }}
        with:
          snap: ${{ needs.build.outputs.snap-file }}
          release: ${{ env.RELEASE }}
